name: torchreid
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - asttokens=3.0.0=pyhd8ed1ab_1
  - backcall=0.2.0=pyhd3eb1b0_1
  - blas=1.0=mkl
  - brotlicffi=1.0.9.2=py39h885b0b7_2
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - certifi=2025.10.5=py39haa95532_0
  - cffi=2.0.0=py39h02ab6af_0
  - charset-normalizer=3.4.4=py39haa95532_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - cpython=3.9.23=py39hd8ed1ab_0
  - cuda-cccl=12.9.27=0
  - cuda-cccl_win-64=12.9.27=0
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.9.19=0
  - cuda-opencl-dev=12.9.19=0
  - cuda-profiler-api=12.9.79=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.9=3
  - debugpy=1.8.16=py39h885b0b7_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - expat=2.7.3=h9214b88_0
  - filelock=3.17.0=py39haa95532_0
  - freetype=2.13.3=h0620614_0
  - giflib=5.2.2=h7edc060_0
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.1=py39h827c3e9_0
  - idna=3.11=py39haa95532_0
  - importlib_metadata=8.5.0=hd3eb1b0_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=6.30.1=pyh3521513_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=py39haa95532_0
  - jpeg=9f=ha349fce_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh5737063_0
  - khronos-opencl-icd-loader=2025.07.22=h79b28c9_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.16=hb4a4139_0
  - lerc=3.0=hd77b12b_0
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcurand=10.3.10.19=0
  - libcurand-dev=10.3.10.19=0
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_1
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=12.1.1.14=0
  - libpng=1.6.50=h46444df_0
  - libsodium=1.0.20=hc70643c_0
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.48.0=h827c3e9_0
  - libwebp=1.3.2=hbc33d0d_0
  - libwebp-base=1.3.2=h3d04722_1
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=3.0.2=py39h827c3e9_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py39h827c3e9_2
  - mkl_fft=1.3.11=py39h827c3e9_0
  - mkl_random=1.2.8=py39hc64d2fc_0
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpmath=1.3.0=py39haa95532_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.2.1=py39haa95532_0
  - opencl-headers=2025.07.22=h885b0b7_0
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.6.0=h725018a_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.3=pyhc872135_0
  - psutil=7.0.0=py39ha55e580_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.23=py39haa95532_0
  - pysocks=1.7.1=py39haa95532_1
  - python=3.9.25=h716150d_1
  - python_abi=3.9=2_cp39
  - pytorch=2.5.1=py3.9_cuda12.1_cudnn9_0
  - pytorch-cuda=12.1=hde6ce7c_6
  - pytorch-mutex=1.0=cuda
  - pywin32=311=py39h885b0b7_0
  - requests=2.32.5=py39haa95532_0
  - setuptools=80.9.0=py39haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sympy=1.14.0=py39haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.15=hf199647_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=py39haa95532_0
  - typing_extensions=4.15.0=py39haa95532_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py39haa95532_0
  - win_inet_pton=1.1.0=py39haa95532_1
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=h6c54ac7_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - annotated-types==0.7.0
      - arrow==1.4.0
      - attrs==25.4.0
      - beautifulsoup4==4.14.3
      - boto3==1.42.36
      - botocore==1.42.36
      - bravado==11.1.0
      - bravado-core==6.1.1
      - click==8.0.3
      - comm==0.2.1
      - cycler==0.11.0
      - cython==3.0.10
      - eval-type-backport==0.3.1
      - executing==2.2.0
      - fonttools==4.28.5
      - fqdn==1.5.1
      - future==1.0.0
      - gdown==5.2.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - importlib-metadata==4.10.1
      - importlib-resources==6.5.2
      - ipython==8.15.0
      - isoduration==20.11.0
      - jmespath==1.1.0
      - joblib==1.2.0
      - jsonpointer==3.0.0
      - jsonref==1.1.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.3.2
      - lark==1.3.1
      - matplotlib==3.5.1
      - monotonic==1.6
      - msgpack==1.1.2
      - mypy-extensions==0.4.3
      - neptune==1.14.0
      - numpy==1.22.0
      - oauthlib==3.3.1
      - packaging==21.3
      - pandas==2.0.3
      - pathspec==0.9.0
      - pillow==10.0.1
      - platformdirs==4.3.7
      - prefetch-generator==1.0.1
      - prompt-toolkit==3.0.51
      - protobuf==6.33.2
      - pyaml==21.10.1
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.19.1
      - pyjwt==2.10.1
      - pyparsing==3.0.6
      - python-dateutil==2.8.2
      - pytz==2025.2
      - pyyaml==6.0
      - pyzmq==27.0.2
      - referencing==0.36.2
      - requests-oauthlib==2.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.27.1
      - s3transfer==0.16.0
      - scikit-learn==1.0.2
      - scipy==1.7.3
      - sentry-sdk==2.48.0
      - simplejson==3.20.2
      - six==1.16.0
      - smmap==5.0.2
      - soupsieve==2.8.3
      - swagger-spec-validator==3.0.4
      - threadpoolctl==3.0.0
      - tomli==1.2.3
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - tornado==6.5.1
      - tqdm==4.62.3
      - typed-ast==1.5.1
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - uri-template==1.3.0
      - urllib3==1.26.20
      - wandb==0.23.1
      - webcolors==24.11.1
      - websocket-client==1.9.0
      - zipp==3.7.0
prefix: E:\Anaconda\envs\torchreid
