name: torchreid
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - asttokens=3.0.0
  - backcall=0.2.0
  - blas=1.0
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - ca-certificates
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - colorama=0.4.6
  - cpython=3.9.23
  - cuda-cccl=12.9.27
  - cuda-cccl_win-64=12.9.27
  - cuda-cudart=12.1.105
  - cuda-cudart-dev=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-libraries-dev=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvrtc-dev=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.9.19
  - cuda-opencl-dev=12.9.19
  - cuda-profiler-api=12.9.79
  - cuda-runtime=12.1.0
  - cuda-version=12.9
  - debugpy=1.8.16
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - expat=2.7.3
  - filelock=3.17.0
  - freetype=2.13.3
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - idna=3.11
  - importlib_metadata=8.5.0
  - intel-openmp=2023.1.0
  - ipykernel=6.30.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - jpeg=9f
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=3.0
  - libcublas=12.1.0.26
  - libcublas-dev=12.1.0.26
  - libcufft=11.0.2.4
  - libcufft-dev=11.0.2.4
  - libcurand=10.3.10.19
  - libcurand-dev=10.3.10.19
  - libcusolver=11.4.4.55
  - libcusolver-dev=11.4.4.55
  - libcusparse=12.0.2.55
  - libcusparse-dev=12.0.2.55
  - libdeflate=1.17
  - libffi=3.4.4
  - libjpeg-turbo=2.0.0
  - libnpp=12.0.2.50
  - libnpp-dev=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjitlink-dev=12.1.105
  - libnvjpeg=12.1.1.14
  - libnvjpeg-dev=12.1.1.14
  - libpng=1.6.50
  - libsodium=1.0.20
  - libtiff=4.5.1
  - libuv=1.48.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - nest-asyncio=1.6.0
  - networkx=3.2.1
  - opencl-headers
  - openjpeg=2.5.2
  - openssl=3.6.0
  - parso=0.8.4
  - pickleshare=0.7.5
  - pip=25.3
  - psutil=7.0.0
  - pure_eval=0.2.3
  - pycparser=2.23
  - pysocks=1.7.1
  - python=3.9.25
  - python_abi=3.9
  - pytorch=2.5.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0=cuda
  - pywin32=311
  - requests=2.32.5
  - setuptools=80.9.0
  - sqlite=3.51.0
  - stack_data=0.6.3
  - sympy=1.14.0
  - tbb=2021.8.0
  - tk=8.6.15
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - annotated-types==0.7.0
      - arrow==1.4.0
      - attrs==25.4.0
      - beautifulsoup4==4.14.3
      - boto3==1.42.36
      - botocore==1.42.36
      - bravado==11.1.0
      - bravado-core==6.1.1
      - click==8.0.3
      - comm==0.2.1
      - cycler==0.11.0
      - cython==3.0.10
      - eval-type-backport==0.3.1
      - executing==2.2.0
      - fonttools==4.28.5
      - fqdn==1.5.1
      - future==1.0.0
      - gdown==5.2.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - importlib-metadata==4.10.1
      - importlib-resources==6.5.2
      - ipython==8.15.0
      - isoduration==20.11.0
      - jmespath==1.1.0
      - joblib==1.2.0
      - jsonpointer==3.0.0
      - jsonref==1.1.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.3.2
      - lark==1.3.1
      - matplotlib==3.5.1
      - monotonic==1.6
      - msgpack==1.1.2
      - mypy-extensions==0.4.3
      - neptune==1.14.0
      - numpy==1.22.0
      - oauthlib==3.3.1
      - packaging==21.3
      - pandas==2.0.3
      - pathspec==0.9.0
      - pillow==10.0.1
      - platformdirs==4.3.7
      - prefetch-generator==1.0.1
      - prompt-toolkit==3.0.51
      - protobuf==6.33.2
      - pyaml==21.10.1
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.19.1
      - pyjwt==2.10.1
      - pyparsing==3.0.6
      - python-dateutil==2.8.2
      - pytz==2025.2
      - pyyaml==6.0
      - pyzmq==27.0.2
      - referencing==0.36.2
      - requests-oauthlib==2.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.27.1
      - s3transfer==0.16.0
      - scikit-learn==1.0.2
      - scipy==1.7.3
      - sentry-sdk==2.48.0
      - simplejson==3.20.2
      - six==1.16.0
      - smmap==5.0.2
      - soupsieve==2.8.3
      - swagger-spec-validator==3.0.4
      - threadpoolctl==3.0.0
      - tomli==1.2.3
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - tornado==6.5.1
      - tqdm==4.62.3
      - typed-ast==1.5.1
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - uri-template==1.3.0
      - urllib3==1.26.20
      - wandb==0.23.1
      - webcolors==24.11.1
      - websocket-client==1.9.0
      - zipp==3.7.0
